towers: 
  fire_tower:
    damage: 6
    damage_to_nearby: 3
    range: 3  
    attack_rate: 3 # 1 lanzamiento cada 3 segundos
    reach: 1 # alcance de impacto
    range_upgrade: 1
    damage_upgrade: 6
    damage_to_nearby_upgrade: 3
    reach_upgrade: 1
    range_base: 6
    range_exponent : 0
    dmg_base: 100
    dmg_exponent: 1.5
    reach_base: 500
    reach_exponent: 2

  earth_tower:
    damage: 20
    range: 2
    attack_rate: 5
    damage_upgrade: 10
    range_upgrade: 1
    range_base: 500
    range_exponent : 2
    dmg_base: 100
    dmg_exponent: 1.5

  water_tower:
    damage: 4
    range: 3
    speed_reduction: 25
    speed_reduction_duration: 2
    attack_rate: 3
    damage_upgrade: 4
    range_upgrade: 1
    speed_reduction_upgrade: 25
    speed_reduction_duration_upgrade: 1
    range_base: 100
    range_exponent : 2
    dmg_base: 100
    dmg_exponent: 1.5
    speed_reduction_base: 100
    speed_reduction_exponent: 2

  air_tower:
    damage: 2
    damage_to_flying: 10
    range: 5
    attack_rate: 5
    range_upgrade: 1
    damage_upgrade: 2
    damage_to_flying_upgrade: 10
    range_base: 100
    range_exponent : 2
    dmg_base: 100
    dmg_exponent: 1.5

enemies:
    green_demon:
        health: 300
        speed: 1
        fly: false
    abmonible:
        health: 200
        speed: 1
        fly: false
    bloody_hawk:
        health: 100
        speed: 4
        fly: true
    goat_man:
        health: 100
        speed: 2
        fly: false
    spectrum:
        health: 100
        speed: 6
        fly: true
    undead:
        health: 20
        speed: 10
        fly: false

spells:
    terraforming:
        cooldown: 20
    fissure:
        duration: 1
        cooldown: 40
    meteorite:
        damage: 30
        damage_to_nearby_units: 10
        reach_of_impact: 2
        cooldown: 20
    fire_wall:
        damage: 10
        duration: 5
        cooldown: 10
    freezing:
        duration: 5
        cooldown: 15
    blizzard:
        damage: 5
        duration: 5
        slowdown: 25
        slowdown_duration: 2
        cooldown: 20
    tornado:
        min_damage: 1
        max_damage: 50
        duration: 10
        cooldown: 20
    ray:
        min_damage: 1
        max_damage: 50
        cooldown: 10