#include "VectorDeSprites.h"


void VectorDeSprites::cargarSprite(const char *direccion) {
    try { //ver esto.
        sprites.push_back(Gdk::Pixbuf::create_from_file(direccion));
    }
    catch (const Gio::ResourceError &ex) {
        std::cerr << "ResourceError: " << ex.what() << std::endl;
    }
    catch (const Gdk::PixbufError &ex) {
        std::cerr << "PixbufError: " << ex.what() << std::endl;
    }
}

VectorDeSprites::VectorDeSprites() {
    cargarSprite("../Resources/Sprites/PisoFirme.png");
    cargarSprite("../Resources/Sprites/TorreDeTierra.png");
    cargarSprite("../Resources/Sprites/SueloLava1.png");
    cargarSprite("../Resources/Sprites/SueloLava2.png");
    cargarSprite("../Resources/Sprites/SueloLava3.png");
    cargarSprite("../Resources/Sprites/SueloLava4.png");
    cargarSprite("../Resources/Sprites/SueloEnemigo.png");
    cargarSprite("../Resources/Sprites/TorreDeFuego.png");
    cargarSprite("../Resources/Sprites/TorreFuego1.png");
    cargarSprite("../Resources/Sprites/TorreFuego2.png");
    cargarSprite("../Resources/Sprites/TorreFuego3.png");
    cargarSprite("../Resources/Sprites/TorreDeAgua.png");
    cargarSprite("../Resources/Sprites/TorreAgua1.png");
    cargarSprite("../Resources/Sprites/TorreAgua2.png");
    cargarSprite("../Resources/Sprites/TorreAgua3.png");
    cargarSprite("../Resources/Sprites/TorreDeAire.png");
    cargarSprite("../Resources/Sprites/TorreAire1.png");
    cargarSprite("../Resources/Sprites/TorreAire2.png");
    cargarSprite("../Resources/Sprites/TorreAire3.png");
    cargarSprite("../Resources/Sprites/PortalAzul.png");
    cargarSprite("../Resources/Sprites/PortalAzul1.png");
    cargarSprite("../Resources/Sprites/PortalAzul2.png");
    cargarSprite("../Resources/Sprites/PortalAzul3.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante1.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante2.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante3.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante4.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante5.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante6.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante7.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante8.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante9.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante10.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante11.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante12.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante13.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante14.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante15.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante16.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante17.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante18.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante19.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante20.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante21.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante22.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante23.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante24.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante25.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante26.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante27.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante28.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante29.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante30.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante31.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante32.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante33.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante34.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante35.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante36.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante37.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante38.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante39.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante40.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante41.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante42.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante43.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante44.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante45.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante46.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante47.png");
    cargarSprite("../Resources/Sprites/AbmonibleCaminarAdelante48.png");
    cargarSprite("../Resources/Sprites/Decierto1.png");
    cargarSprite("../Resources/Sprites/Decierto2.png");
    cargarSprite("../Resources/Sprites/Decierto3.png");
    cargarSprite("../Resources/Sprites/Decierto4.png");
    cargarSprite("../Resources/Sprites/Pradera1.png");
    cargarSprite("../Resources/Sprites/Pradera2.png");
    cargarSprite("../Resources/Sprites/Pradera3.png");
    cargarSprite("../Resources/Sprites/Pradera4.png");
    cargarSprite("../Resources/Sprites/SueloGelido1.png");
    cargarSprite("../Resources/Sprites/SueloGelido2.png");
    cargarSprite("../Resources/Sprites/SueloGelido3.png");
    cargarSprite("../Resources/Sprites/SueloGelido4.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_01.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_02.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_03.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_04.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_05.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_06.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_07.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_08.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_09.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_10.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_11.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_12.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_13.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_14.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_15.png");
    cargarSprite("../Resources/Sprites/AataqueDeAgua_16.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_01.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_02.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_03.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_04.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_05.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_06.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_07.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_08.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_09.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_10.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_11.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_12.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_13.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_14.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_15.png");
    cargarSprite("../Resources/Sprites/AtaqueDeAire_16.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_01.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_02.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_03.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_04.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_05.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_06.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_07.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_08.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_09.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_10.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_11.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_12.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_13.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_14.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_15.png");
    cargarSprite("../Resources/Sprites/AtaqueDeFuego_16.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_01.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_02.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_03.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_04.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_05.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_06.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_07.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_08.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_09.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_10.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_11.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_12.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_13.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_14.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_15.png");
    cargarSprite("../Resources/Sprites/AtaqueDeTierra_09_16.png");
    cargarSprite("../Resources/Sprites/Aguila (1).png");
    cargarSprite("../Resources/Sprites/Aguila (2).png");
    cargarSprite("../Resources/Sprites/Aguila (3).png");
    cargarSprite("../Resources/Sprites/Aguila (4).png");
    cargarSprite("../Resources/Sprites/Aguila (5).png");
    cargarSprite("../Resources/Sprites/Aguila (6).png");
    cargarSprite("../Resources/Sprites/Aguila (7).png");
    cargarSprite("../Resources/Sprites/Aguila (8).png");
    cargarSprite("../Resources/Sprites/Aguila (9).png");
    cargarSprite("../Resources/Sprites/Aguila (10).png");
    cargarSprite("../Resources/Sprites/Aguila (11).png");
    cargarSprite("../Resources/Sprites/Aguila (12).png");
    cargarSprite("../Resources/Sprites/Aguila (13).png");
    cargarSprite("../Resources/Sprites/Aguila (14).png");
    cargarSprite("../Resources/Sprites/Aguila (15).png");
    cargarSprite("../Resources/Sprites/Aguila (16).png");
    cargarSprite("../Resources/Sprites/Aguila (17).png");
    cargarSprite("../Resources/Sprites/Aguila (18).png");
    cargarSprite("../Resources/Sprites/Aguila (19).png");
    cargarSprite("../Resources/Sprites/Aguila (20).png");
    cargarSprite("../Resources/Sprites/Aguila (21).png");
    cargarSprite("../Resources/Sprites/Aguila (22).png");
    cargarSprite("../Resources/Sprites/Aguila (23).png");
    cargarSprite("../Resources/Sprites/Aguila (24).png");
    cargarSprite("../Resources/Sprites/Aguila (25).png");
    cargarSprite("../Resources/Sprites/Aguila (26).png");
    cargarSprite("../Resources/Sprites/Aguila (27).png");
    cargarSprite("../Resources/Sprites/Aguila (28).png");
    cargarSprite("../Resources/Sprites/Aguila (29).png");
    cargarSprite("../Resources/Sprites/Aguila (30).png");
    cargarSprite("../Resources/Sprites/Aguila (31).png");
    cargarSprite("../Resources/Sprites/Aguila (32).png");
    cargarSprite("../Resources/Sprites/Cabra (17).png");
    cargarSprite("../Resources/Sprites/Cabra (18).png");
    cargarSprite("../Resources/Sprites/Cabra (19).png");
    cargarSprite("../Resources/Sprites/Cabra (20).png");
    cargarSprite("../Resources/Sprites/Cabra (21).png");
    cargarSprite("../Resources/Sprites/Cabra (22).png");
    cargarSprite("../Resources/Sprites/Cabra (23).png");
    cargarSprite("../Resources/Sprites/Cabra (24).png");
    cargarSprite("../Resources/Sprites/Cabra (25).png");
    cargarSprite("../Resources/Sprites/Cabra (26).png");
    cargarSprite("../Resources/Sprites/Cabra (27).png");
    cargarSprite("../Resources/Sprites/Cabra (28).png");
    cargarSprite("../Resources/Sprites/Cabra (29).png");
    cargarSprite("../Resources/Sprites/Cabra (30).png");
    cargarSprite("../Resources/Sprites/Cabra (31).png");
    cargarSprite("../Resources/Sprites/Cabra (32).png");
    cargarSprite("../Resources/Sprites/Cabra (1).png");
    cargarSprite("../Resources/Sprites/Cabra (2).png");
    cargarSprite("../Resources/Sprites/Cabra (3).png");
    cargarSprite("../Resources/Sprites/Cabra (4).png");
    cargarSprite("../Resources/Sprites/Cabra (5).png");
    cargarSprite("../Resources/Sprites/Cabra (6).png");
    cargarSprite("../Resources/Sprites/Cabra (7).png");
    cargarSprite("../Resources/Sprites/Cabra (8).png");
    cargarSprite("../Resources/Sprites/Cabra (9).png");
    cargarSprite("../Resources/Sprites/Cabra (10).png");
    cargarSprite("../Resources/Sprites/Cabra (11).png");
    cargarSprite("../Resources/Sprites/Cabra (12).png");
    cargarSprite("../Resources/Sprites/Cabra (13).png");
    cargarSprite("../Resources/Sprites/Cabra (14).png");
    cargarSprite("../Resources/Sprites/Cabra (15).png");
    cargarSprite("../Resources/Sprites/Cabra (16).png");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (1).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (2).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (3).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (4).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (5).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (6).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (7).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (8).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (9).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (10).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (11).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (12).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (13).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (14).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (15).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (16).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (17).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (18).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (19).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (20).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (21).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (22).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (23).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (24).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (25).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (26).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (27).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (28).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (29).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (30).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (31).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (32).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (33).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (34).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (35).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (36).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (37).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (38).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (39).gif");
    cargarSprite("../Resources/Sprites/DemonioVerdeCaminando (40).gif");
    cargarSprite("../Resources/Sprites/espectro (21).png");
    cargarSprite("../Resources/Sprites/espectro (22).png");
    cargarSprite("../Resources/Sprites/espectro (23).png");
    cargarSprite("../Resources/Sprites/espectro (24).png");
    cargarSprite("../Resources/Sprites/espectro (25).png");
    cargarSprite("../Resources/Sprites/espectro (26).png");
    cargarSprite("../Resources/Sprites/espectro (27).png");
    cargarSprite("../Resources/Sprites/espectro (28).png");
    cargarSprite("../Resources/Sprites/espectro (29).png");
    cargarSprite("../Resources/Sprites/espectro (30).png");
    cargarSprite("../Resources/Sprites/espectro (31).png");
    cargarSprite("../Resources/Sprites/espectro (32).png");
    cargarSprite("../Resources/Sprites/espectro (33).png");
    cargarSprite("../Resources/Sprites/espectro (34).png");
    cargarSprite("../Resources/Sprites/espectro (35).png");
    cargarSprite("../Resources/Sprites/espectro (36).png");
    cargarSprite("../Resources/Sprites/espectro (37).png");
    cargarSprite("../Resources/Sprites/espectro (38).png");
    cargarSprite("../Resources/Sprites/espectro (39).png");
    cargarSprite("../Resources/Sprites/espectro (40).png");
    cargarSprite("../Resources/Sprites/espectro (1).png");
    cargarSprite("../Resources/Sprites/espectro (2).png");
    cargarSprite("../Resources/Sprites/espectro (3).png");
    cargarSprite("../Resources/Sprites/espectro (4).png");
    cargarSprite("../Resources/Sprites/espectro (5).png");
    cargarSprite("../Resources/Sprites/espectro (6).png");
    cargarSprite("../Resources/Sprites/espectro (7).png");
    cargarSprite("../Resources/Sprites/espectro (8).png");
    cargarSprite("../Resources/Sprites/espectro (9).png");
    cargarSprite("../Resources/Sprites/espectro (10).png");
    cargarSprite("../Resources/Sprites/espectro (11).png");
    cargarSprite("../Resources/Sprites/espectro (12).png");
    cargarSprite("../Resources/Sprites/espectro (13).png");
    cargarSprite("../Resources/Sprites/espectro (14).png");
    cargarSprite("../Resources/Sprites/espectro (15).png");
    cargarSprite("../Resources/Sprites/espectro (16).png");
    cargarSprite("../Resources/Sprites/espectro (17).png");
    cargarSprite("../Resources/Sprites/espectro (18).png");
    cargarSprite("../Resources/Sprites/espectro (19).png");
    cargarSprite("../Resources/Sprites/espectro (20).png");
    cargarSprite("../Resources/Sprites/Esqueleto (13).png");
    cargarSprite("../Resources/Sprites/Esqueleto (14).png");
    cargarSprite("../Resources/Sprites/Esqueleto (15).png");
    cargarSprite("../Resources/Sprites/Esqueleto (16).png");
    cargarSprite("../Resources/Sprites/Esqueleto (17).png");
    cargarSprite("../Resources/Sprites/Esqueleto (18).png");
    cargarSprite("../Resources/Sprites/Esqueleto (19).png");
    cargarSprite("../Resources/Sprites/Esqueleto (20).png");
    cargarSprite("../Resources/Sprites/Esqueleto (21).png");
    cargarSprite("../Resources/Sprites/Esqueleto (22).png");
    cargarSprite("../Resources/Sprites/Esqueleto (23).png");
    cargarSprite("../Resources/Sprites/Esqueleto (24).png");
    cargarSprite("../Resources/Sprites/Esqueleto (1).png");
    cargarSprite("../Resources/Sprites/Esqueleto (2).png");
    cargarSprite("../Resources/Sprites/Esqueleto (3).png");
    cargarSprite("../Resources/Sprites/Esqueleto (4).png");
    cargarSprite("../Resources/Sprites/Esqueleto (5).png");
    cargarSprite("../Resources/Sprites/Esqueleto (6).png");
    cargarSprite("../Resources/Sprites/Esqueleto (7).png");
    cargarSprite("../Resources/Sprites/Esqueleto (8).png");
    cargarSprite("../Resources/Sprites/Esqueleto (9).png");
    cargarSprite("../Resources/Sprites/Esqueleto (10).png");
    cargarSprite("../Resources/Sprites/Esqueleto (11).png");
    cargarSprite("../Resources/Sprites/Esqueleto (12).png");
    cargarSprite("../Resources/Sprites/grieta_01.png");
    cargarSprite("../Resources/Sprites/grieta_02.png");
    cargarSprite("../Resources/Sprites/grieta_03.png");
    cargarSprite("../Resources/Sprites/grieta_04.png");
    cargarSprite("../Resources/Sprites/grieta_05.png");
    cargarSprite("../Resources/Sprites/grieta_06.png");
    cargarSprite("../Resources/Sprites/grieta_07.png");
    cargarSprite("../Resources/Sprites/grieta_08.png");
    cargarSprite("../Resources/Sprites/Meteorito_01.png");
    cargarSprite("../Resources/Sprites/Meteorito_02.png");
    cargarSprite("../Resources/Sprites/Meteorito_03.png");
    cargarSprite("../Resources/Sprites/Meteorito_04.png");
    cargarSprite("../Resources/Sprites/Meteorito_05.png");
    cargarSprite("../Resources/Sprites/Meteorito_06.png");
    cargarSprite("../Resources/Sprites/Meteorito_07.png");
    cargarSprite("../Resources/Sprites/Meteorito_08.png");
    cargarSprite("../Resources/Sprites/Meteorito_09.png");
    cargarSprite("../Resources/Sprites/Meteorito_10.png");
    cargarSprite("../Resources/Sprites/Meteorito_11.png");
    cargarSprite("../Resources/Sprites/Meteorito_12.png");
    cargarSprite("../Resources/Sprites/Meteorito_13.png");
    cargarSprite("../Resources/Sprites/Meteorito_14.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_01.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_02.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_03.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_04.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_05.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_06.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_07.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_08.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_09.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_10.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_11.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_12.png");
    cargarSprite("../Resources/Sprites/MuroDeFuego_13.png");
    cargarSprite("../Resources/Sprites/Rayo_01.png");
    cargarSprite("../Resources/Sprites/Rayo_02.png");
    cargarSprite("../Resources/Sprites/Rayo_03.png");
    cargarSprite("../Resources/Sprites/Rayo_04.png");
    cargarSprite("../Resources/Sprites/Rayo_05.png");
    cargarSprite("../Resources/Sprites/Rayo_06.png");
    cargarSprite("../Resources/Sprites/Rayo_07.png");
    cargarSprite("../Resources/Sprites/Rayo_08.png");
    cargarSprite("../Resources/Sprites/Rayo_09.png");
    cargarSprite("../Resources/Sprites/Rayo_10.png");
    cargarSprite("../Resources/Sprites/Rayo_11.png");
    cargarSprite("../Resources/Sprites/Rayo_12.png");
    cargarSprite("../Resources/Sprites/Rayo_13.png");
    cargarSprite("../Resources/Sprites/Rayo_14.png");
    cargarSprite("../Resources/Sprites/Rayo_15.png");
    cargarSprite("../Resources/Sprites/Rayo_16.png");
    cargarSprite("../Resources/Sprites/Tornado_01.png");
    cargarSprite("../Resources/Sprites/Tornado_02.png");
    cargarSprite("../Resources/Sprites/Tornado_03.png");
    cargarSprite("../Resources/Sprites/Tornado_04.png");
    cargarSprite("../Resources/Sprites/Tornado_05.png");
    cargarSprite("../Resources/Sprites/Tornado_06.png");
    cargarSprite("../Resources/Sprites/Tornado_07.png");
    cargarSprite("../Resources/Sprites/Tornado_08.png");
    cargarSprite("../Resources/Sprites/Tornado_09.png");
    cargarSprite("../Resources/Sprites/Tornado_10.png");
    cargarSprite("../Resources/Sprites/Tornado_11.png");
    cargarSprite("../Resources/Sprites/Tornado_12.png");
    cargarSprite("../Resources/Sprites/Tornado_13.png");
    cargarSprite("../Resources/Sprites/Tornado_14.png");
    cargarSprite("../Resources/Sprites/Tornado_15.png");

    cargarSprite("../Resources/Sprites/PoertalAzul2_01.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_02.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_03.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_04.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_05.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_06.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_07.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_08.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_09.png");
    cargarSprite("../Resources/Sprites/PoertalAzul2_10.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_01.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_02.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_03.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_04.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_05.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_06.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_07.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_08.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_09.png");
    cargarSprite("../Resources/Sprites/PoertalRojo2_10.png");

    cargarSprite("../Resources/Sprites/PortaAzul1_01.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_02.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_03.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_04.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_05.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_06.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_07.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_08.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_09.png");
    cargarSprite("../Resources/Sprites/PortaAzul1_10.png");
    cargarSprite("../Resources/Sprites/PortaRojo1.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_01.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_02.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_03.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_04.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_05.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_06.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_07.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_08.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_09.png");
    cargarSprite("../Resources/Sprites/PortaRojo1_10.png");
    cargarSprite("../Resources/Sprites/Metorito (1).png");
    cargarSprite("../Resources/Sprites/Metorito (3).png");
    cargarSprite("../Resources/Sprites/Metorito (4).png");
    cargarSprite("../Resources/Sprites/Metorito (5).png");
    cargarSprite("../Resources/Sprites/Metorito (6).png");
    cargarSprite("../Resources/Sprites/Metorito (7).png");
    cargarSprite("../Resources/Sprites/Metorito (8).png");
    cargarSprite("../Resources/Sprites/Metorito (9).png");
    cargarSprite("../Resources/Sprites/Metorito (10).png");
    cargarSprite("../Resources/Sprites/Metorito (11).png");
    cargarSprite("../Resources/Sprites/Metorito (12).png");
    cargarSprite("../Resources/Sprites/Metorito (13).png");
    cargarSprite("../Resources/Sprites/Metorito (14).png");
    cargarSprite("../Resources/Sprites/Metorito (15).png");
    cargarSprite("../Resources/Sprites/Metorito (16).png");
    cargarSprite("../Resources/Sprites/Metorito (2).png"); //ping
}

Glib::RefPtr<Gdk::Pixbuf> &VectorDeSprites::obtener(int n) {
    return (sprites[n]);
}
